version: "3.9"

services:

  # Guide API service
  guide-api:
    environment:
      CORS_ALLOWED_ORIGINS: "*"
      TELEGRAM_WEB_APP_URL: https://${NGROK_DOMAIN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    restart: on-failure
    build:
      context: ./api

  # Guide UI service
  guide-ui:
    restart: on-failure
    build:
      context: ./ui

  dev-proxy:
    image: nginx:stable-alpine
    environment:
      PORT: 3000
      API_URL: http://guide-api:3000
      UI_URL: http://guide-ui:3000
    volumes:
      - ./proxy.template:/etc/nginx/templates/default.conf.template

  # Ngrok service
  ngrok:
    image: ngrok/ngrok:alpine
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: ["http", "--domain=${NGROK_DOMAIN}", "dev-proxy:3000", "--log=stdout"]
    

